### ISSUE TITLE
missing dependency to orocos/pcl

### ISSUE THREAD

**Issue by planthaber** [rock-gui/gui-vizkit3d_pcl#1]
/data/jenkins/workspace/workspace/rock-complete-incremental/Flavor/master/node/Debian_stable/dev/gui/vizkit3d_pcl/viz/PCLPointCloudVisualization.hpp:8:35: fatal error: orocos/pcl/pclTypes.hpp: No such file or directory
       `#include <orocos/pcl/pclTypes.hpp>`

**Comment by saarnold** [comment]
Fixed by rock-gui/gui-vizkit3d_pcl#2
The include is obsolete, it doesn't need a dependency to the orocos component.
