### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by AlexanderFabisch** [rock-gui/gui-vizkit3d_pcl#4]
Hi,

I would like to use this plugin in my lightweight docker container for EnviRe. Unfortunately, it depends on

slam/orogen/pcl -> base/orogen/types -> slam/orogen/pcl -> base/orogen/std -> orogen -> rtt ...

Why is slam/orogen/pcl a dependency of this package? Could we make it at least optional?

@saarnold

**Comment by saarnold** [comment]
No we can completely remove it, there is no need to depend on any orogen components for this package.

**Comment by saarnold** [comment]
Was fixed on master, thanks for reporting.
